---
- hosts: localhost
  become: true
  tasks:
    - name: Download dpkg-dev package
      get_url:
        url: "http://archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.21.1ubuntu2.2_all.deb"
        dest: "/tmp/dpkg-dev_1.21.1ubuntu2.2_all.deb"

    - name: Install dpkg-dev package
      apt:
        deb: "/tmp/dpkg-dev_1.21.1ubuntu2.2_all.deb"
        state: present
