---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - curl
    - jq

- name: Download k0s binary
  get_url:
    url: "https://github.com/k0sproject/k0s/releases/download/v1.27.4%2Bk0s.0/k0s-v1.27.4+k0s.0-amd64"
    dest: /usr/local/bin/k0s
    mode: '0755' 
  become: yes

 

